bump version

diff --git a/bin/tumblr-gif b/bin/tumblr-gif
--- a/bin/tumblr-gif
+++ b/bin/tumblr-gif
@@ -1,12 +1,12 @@
 #!/bin/bash
 # ---------------------------------------------
 # Artifact:     tumblr-gif/tumblr-gif
-# Version:      0.2.0
-# Date (UTC):   Tue, 25 Feb 2014 12:53:27 +0000
+# Version:      1.0.0
+# Date (UTC):   Tue, 25 Feb 2014 15:47:43 +0000
 # Generated by: bashing 0.2.0
 # ---------------------------------------------
 export __BASHING_VERSION='0.2.0'
-export __VERSION='0.2.0'
+export __VERSION='1.0.0'
 export __ARTIFACT_ID='tumblr-gif'
 export __GROUP_ID='tumblr-gif'
 set -eu
@@ -55,69 +55,77 @@ function clean_files() {
 MAX_FILE_SIZE=$((990 * 1000)) # 990 KB
 MIN_FILE_SIZE=$((985 * 1000)) # 990 KB
 MAX_SIDE=500
-MIN_SIDE=230
 function do_convert() {
+    if [[ $MIN_FILE_SIZE -gt $MAX_FILE_SIZE ]]; then
+        abort "ERROR: invalid MIN/MAX_FILE_SIZE: ${MIN_FILE_SIZE}/${MAX_FILE_SIZE}"
+    elif [[ $(list_frames | wc -l) -lt $frame_interval ]]; then
+        abort "ERROR: too less images"
+    fi
+    printf '  %s images, %sB (avg: %sKB)\n' \
+        $(list_frames | wc -l) \
+        $(du -sh $WORKSPACE | cut -f1) \
+        $(bc <<< "$(du -s $WORKSPACE | cut -f1) / $(ls $WORKSPACE/* | wc -l)")
+    rm_blendeds
+    if [[ $blend_loop -gt 0 ]]; then
+        gen_blendeds
+    fi
     gen_gif $init_width
-    local sides="$(get_geometry)"
-    local base_width=$(cut -dx -f1 <<< "$sides")
-    local base_height=$(cut -dx -f2 <<< "$sides")
-    if [[ $base_width -eq $MAX_SIDE || $base_height -eq $MAX_SIDE ]] \
-        && [[ $(stat -c%s "$output_gif") -lt $MAX_FILE_SIZE ]]; then
+    if is_valid_gif; then
         echo "Success!"
         return 0
     fi
-    if is_valid_sides $base_width $base_height && is_valid_size; then
-        echo "Success!"
-        return 0
-    fi
-    local width_history=
-    local sides w h
+    local width_history=$(get_width)
+    local sides w
     while true ; do
-        sides="$(next_sides)"
-        w=$(cut -dx -f1 <<< "$sides")
-        h=$(cut -dx -f2 <<< "$sides")
+        w=$(next_width)
         if grep -qF $w <<< "$width_history"; then
-            echo "Width Convergence: ${w}x${h}"
+            echo "GIF width convergence: ${w}x"
             echo "Success?"
             return 0
         else
             width_history="$width_history $w"
         fi
-        if ! is_valid_sides $w $h; then
-            abort "Failure: delete some images on $WORKSPACE"
-        fi
         gen_gif $w
-        if is_valid_size; then
+        if is_valid_gif; then
             break
         fi
     done
     echo "Success"
 }
-function is_valid_size() {
-    local size=$(stat -c%s "$output_gif")
-    [[ $size -lt $MAX_FILE_SIZE \
-        && $size -gt $MIN_FILE_SIZE ]] || return 1
+function list_frames() {
+    ls -- $WORKSPACE | grep -vP '^__blended-\d+\.png$'
+}
+function rm_blendeds() {
+    ls -- $WORKSPACE | grep -P '^__blended-\d+\.png$' | xargs -I{} rm $WORKSPACE/{}
+}
+function is_valid_gif() {
+    local size=$(get_size)
+    local geo=$(get_geometry)
+    local width=$(cut -f1 -dx <<< $geo)
+    local height=$(cut -f2 -dx <<< $geo)
+    ( is_valid_sides $width $height && is_expected_size_range $size) \
+        || ( is_max_sides $width $height && is_valid_size $size)
 }
 function is_valid_sides() {
-    local width=$1
-    local height=$2
-    if [[ $width -gt $height ]]; then # the long side is width
-        if [[ $width -gt $MAX_SIDE ]]; then
-            echo "Too long width"
-            return 1
-        elif [[ $width -lt $MIN_SIDE ]]; then
-            echo "Too short width"
-            return 1
-        fi
-    else # the long side is height
-        if [[ $height -gt $MAX_SIDE ]]; then
-            echo "Too long height"
-            return 1
-        elif [[ $height -lt $MIN_SIDE ]]; then
-            echo "Too short height"
-            return 1
-        fi
+    local w=$1 h=$2
+    if [[ $w -gt $h ]]
+    then [[ $w -le $MAX_SIDE ]]
+    else [[ $h -le $MAX_SIDE ]]
     fi
+}
+function is_expected_size_range() {
+    [[ $1 -le $MAX_FILE_SIZE \
+        && $1 -ge $MIN_FILE_SIZE ]]
+}
+function is_max_sides() {
+    local w=$1 h=$2
+    if [[ $w -gt $h ]]
+    then [[ $w -eq $MAX_SIDE ]]
+    else [[ $h -eq $MAX_SIDE ]]
+    fi
+}
+function is_valid_size() {
+    [[ $1 -le $MAX_FILE_SIZE ]]
 }
 function get_geometry() {
     identify -format '%[fx:w]x%[fx:h]\n' "$output_gif" | head -n 1
@@ -130,41 +138,71 @@ function get_width() {
 function get_size() {
     stat -c%s "$output_gif"
 }
-function next_sides() {
-    local w=$(get_width "$output_gif")
-    local s=$(get_size "$output_gif")
+function next_width() {
+    local geo=$(get_geometry)
+    local w=$(cut -f1 -dx <<< $geo)
+    local h=$(cut -f2 -dx <<< $geo)
+    local s=$(get_size)
     local next_w=$(evenize $(bc -l <<< "sqrt($MAX_FILE_SIZE / $s) * $w"))
     if [[ $next_w -gt $MAX_SIDE ]]; then
         next_w=$MAX_SIDE
     fi
-    next_h=$(((base_height * next_w) / base_width))
+    local next_h=$(((h * next_w) / w))
     if [[ $next_h -gt $MAX_SIDE ]]; then
         next_h=$MAX_SIDE
-        next_w=$(((base_width * next_h) / base_height))
+        next_w=$(((w * next_h) / h))
     fi
-    echo ${next_w}x${next_h}
-    width_history="$width_history $next_w"
+    echo ${next_w}
 }
 function evenize() {
     local i=${1%.*}
     echo $((i / 2 * 2))
 }
-gen_counter=1
-function gen_gif() {
-    local width="$1"
-    local delay=$((delay_factor * frame_interval))
-    local arg="-delay $delay"
-    local last_i=$(ls $WORKSPACE | wc -l)
+function gen_blendeds() {
+    local first_frame="$(get_first_frame)"
+    local last_frame="$(get_last_frame)"
+    local interval=$(( 100 / ( blend_loop + 1 ) ))
+    local percent out
+    for percent in $(seq $interval $interval $((100 - interval))); do
+        out="$WORKSPACE/$(printf '__blended-%02d.png' $percent)"
+        composite -blend $percent $first_frame $last_frame $out
+    done
+}
+function get_first_frame() {
+    echo "$WORKSPACE/$(list_frames | sort -n | head -n 1)"
+}
+function get_last_frame() {
+    local last_i=$(list_frames | wc -l)
     if [[ $((last_i % frame_interval)) -eq 0 ]]
     then last_i=$((last_i - frame_interval))
     else last_i=$(((last_i / frame_interval) * frame_interval))
     fi
     set +x
     local f i=0
-    for f in $(ls $WORKSPACE | sort -n); do
+    for f in $(list_frames | sort -n); do
         if [[ $((i % frame_interval)) -eq 0 ]]; then
             f="$WORKSPACE/$f"
-            if [[ $i -eq $last_i ]]
+            if [[ $i -eq $last_i ]]; then
+                echo "$f"
+                break
+            fi
+        fi
+        i=$((i + 1))
+    done
+    set_x
+}
+gen_counter=1
+function gen_gif() {
+    local width="$1"
+    local delay=$((delay_factor * frame_interval))
+    local arg="-delay $delay"
+    local last_frame=$(get_last_frame)
+    set +x
+    local f i=0
+    for f in $(list_frames | sort -n); do
+        if [[ $((i % frame_interval)) -eq 0 ]]; then
+            f="$WORKSPACE/$f"
+            if [[ "$f" = "$last_frame" ]]
             then arg="$arg -delay $last_delay '$f'"
             else arg="$arg '$f'"
             fi
@@ -172,15 +210,25 @@ function gen_gif() {
         i=$((i + 1))
     done
     set_x
+    if [[ $blend_loop -gt 0 ]]; then
+        arg="$arg -delay $delay"
+        for f in $(list_blendeds | sort -n); do
+            f="$WORKSPACE/$f"
+            arg="$arg '$f'"
+        done
+    fi
     echo_and_eval convert $arg -loop 0 \
         -geometry "${width}x" \
         -fuzz ${fuzz}% \
         -dither FloydSteinberg \
         -modulate "100,$saturation" \
-        -layers optimize "$output_gif"
+        -layers Optimize "$output_gif"
     local s="$(ls -sh "$output_gif"|tail -n 1|awk '{print $1}')"
-    echo -e "#${gen_counter}\t$(get_geometry) \t${s}B";
+    printf '#%d: %7s %4sB\n' $gen_counter $(get_geometry) $s;
     gen_counter=$((gen_counter + 1))
+}
+function list_blendeds() {
+    ls -- "$WORKSPACE" | grep -P '^__blended-\d+\.png$'
 }
 function echo_and_eval() {
     if $is_echo_convert
@@ -251,33 +299,37 @@ function cli_clean() {
   return 0;
 }
 function cli_gen() {
+  saturation=100
+  init_width=500
+  fuzz=2
+  frame_interval=2
+  last_delay=
+  delay_factor=3
+  blend_loop=0
+  is_echo_convert=false
+  output_gif=
   usage="Usage: $(basename "$0") [<option> [ ... ] ] <output_gif>
       -s,--saturation NUM     :
           set this smaller NUM if tumblr return \"Error uploading image\".
-          default: 95, max: 100, min: 1.
-      -w,--init-width NUM     : default: 500
+          default: $saturation, max: 100, min: 1
+      -w,--init-width NUM     : default: $init_width
       -f,--fuzz NUM           :
-          set this smaller NUM then a smaller gif was generated. default: 2.
+          set this smaller NUM then a smaller gif was generated. default: $fuzz
       -i,--frame-interval NUM :
-          set this larger NUM then a smaller gif was generated. default: 1.
+          set this larger NUM then a smaller gif was generated. default: $frame_interval
       -l,--last-delay NUM     :
           set this larger NUM if you want a gif which has the last frame stop
           for NUM delay.
           default: ( delay-factor * frame-interval )
       --delay-factor NUM      :
           set this larger NUM if you want a gif at faster speed animation.
-          default: 3
+          default: $delay_factor
+      -b,--blend-loop NUM     :
+          blending between the first frame and the last frame with NUM frame.
+          default: $blend_loop
       --echo-convert          : output 'convert' cmmands
       -h,--help
   "
-  saturation=95
-  init_width=500
-  fuzz=2
-  frame_interval=2
-  last_delay=
-  delay_factor=3
-  output_gif=
-  is_echo_convert=false
   while [[ $# -gt 0 ]]; do
       case "$1" in
           -s|--saturation)
@@ -310,6 +362,11 @@ function cli_gen() {
               delay_factor=$2
               shift
               ;;
+          --blend-loop)
+              is_int "$2" || abort "$1 argument must integer: $2"
+              blend_loop=$2
+              shift
+              ;;
           --echo-convert)
               is_echo_convert="true"
               ;;
@@ -330,10 +387,10 @@ function cli_gen() {
   fi
   (
       for v in saturation init_width fuzz frame_interval last_delay delay_factor \
-          is_echo_convert output_gif
+          blend_loop is_echo_convert output_gif
       do eval echo "$v : \$$v"
       done
-      echo ---------------
+      echo -------------------
   ) | column -t
   do_convert
   hook_after_gen "$output_gif"
@@ -395,7 +452,7 @@ HELP
       status=0
       ;;
     "version")
-      echo "tumblr-gif 0.2.0 (bash $BASH_VERSION)"
+      echo "tumblr-gif 1.0.0 (bash $BASH_VERSION)"
       status=0
       ;;
     *) echo "Unknown Command: $cmd" 1>&2;;
