Add the function to generate a GIF which is half sides and 2MB limitation

diff --git a/bin/tumblr-gif b/bin/tumblr-gif
--- a/bin/tumblr-gif
+++ b/bin/tumblr-gif
@@ -2,7 +2,7 @@
 # ---------------------------------------------
 # Artifact:     tumblr-gif/tumblr-gif
 # Version:      1.0.1
-# Date (UTC):   Sat, 01 Mar 2014 09:35:23 +0000
+# Date (UTC):   Sat, 12 Jul 2014 08:57:26 +0000
 # Generated by: bashing 0.2.0
 # ---------------------------------------------
 export __BASHING_VERSION='0.2.0'
@@ -44,7 +44,7 @@ function hash_code() {
     bc <<< "$s % $base"
 }
 function err() {
-    echo "$@" >&2
+    echo -e "$@" >&2
 }
 function is_int() {
     [[ "$1" =~ [0-9]+ ]]
@@ -52,10 +52,13 @@ function is_int() {
 function clean_files() {
     rm -vrf -- "$WORKSPACE"/*
 }
-MAX_FILE_SIZE=$((990 * 1000)) # 990 KB
-MIN_FILE_SIZE=$((985 * 1000)) # 990 KB
+MAX_FILE_SIZE=$((995 * 1000)) # 998 KB
+MIN_FILE_SIZE=$((990 * 1000)) # 990 KB
 MAX_SIDE=500
 function do_convert() {
+    if $is_half
+    then update_for_half_limits
+    fi
     if [[ $MIN_FILE_SIZE -gt $MAX_FILE_SIZE ]]; then
         abort "ERROR: invalid MIN/MAX_FILE_SIZE: ${MIN_FILE_SIZE}/${MAX_FILE_SIZE}"
     elif [[ $(list_frames | wc -l) -lt $frame_interval ]]; then
@@ -68,6 +71,10 @@ function do_convert() {
     rm_blendeds
     if [[ $blend_loop -gt 0 ]]; then
         gen_blendeds
+    fi
+    if $is_echo_convert; then
+        echo "$(convert_cmd $init_width)"
+        return 0
     fi
     gen_gif $init_width
     if is_valid_gif; then
@@ -82,6 +89,9 @@ function do_convert() {
             echo "GIF width convergence: ${w}x"
             echo "Success?"
             return 0
+        elif [[ $w -lt $((MAX_SIDE / 2 )) ]]; then
+            abort "ERROR: Too large or many frames to make a GIF\nabort"
+            return 1
         else
             width_history="$width_history $w"
         fi
@@ -91,6 +101,11 @@ function do_convert() {
         fi
     done
     echo "Success"
+}
+function update_for_half_limits() {
+    MAX_FILE_SIZE=$((1998 * 1000)) # 1998 KB
+    MIN_FILE_SIZE=$((1990 * 1000)) # 1990 KB
+    MAX_SIDE=245
 }
 function list_frames() {
     ls -- $WORKSPACE | grep -vP '^__blended-\d+\.png$'
@@ -194,6 +209,16 @@ function get_last_frame() {
 gen_counter=1
 function gen_gif() {
     local width="$1"
+    eval "$(convert_cmd $width)"
+    local s="$(ls -sh "$output_gif"|tail -n 1|awk '{print $1}')"
+    printf '#%d: %7s %4sB\n' $gen_counter $(get_geometry) $s;
+    gen_counter=$((gen_counter + 1))
+}
+function list_blendeds() {
+    ls -- "$WORKSPACE" | grep -P '^__blended-\d+\.png$'
+}
+function convert_cmd() {
+    local width="$1"
     local delay=$((delay_factor * frame_interval))
     local arg="-delay $delay"
     local last_frame=$(get_last_frame)
@@ -217,24 +242,14 @@ function gen_gif() {
             arg="$arg '$f'"
         done
     fi
-    echo_and_eval convert $arg -loop 0 \
-        -geometry "${width}x" \
-        -fuzz ${fuzz}% \
-        -dither FloydSteinberg \
-        -modulate "100,$saturation" \
-        -layers Optimize "$output_gif"
-    local s="$(ls -sh "$output_gif"|tail -n 1|awk '{print $1}')"
-    printf '#%d: %7s %4sB\n' $gen_counter $(get_geometry) $s;
-    gen_counter=$((gen_counter + 1))
-}
-function list_blendeds() {
-    ls -- "$WORKSPACE" | grep -P '^__blended-\d+\.png$'
-}
-function echo_and_eval() {
-    if $is_echo_convert
-    then echo "$@"
+    echo -n "convert $arg -loop 0 "
+    echo -n "-geometry ${width}x "
+    if [[ $fuzz -gt 0 ]]
+    then echo -n "-fuzz ${fuzz}% "
     fi
-    eval "$@"
+    echo -n "-dither FloydSteinberg "
+    echo -n "-modulate 100,$saturation "
+    echo -n "-layers Optimize \"$output_gif\""
 }
 function hook_after_view() {
     [[ $# -gt 0 ]] || return
@@ -299,8 +314,10 @@ function cli_clean() {
   return 0;
 }
 function cli_gen() {
+  DEFAULT_INIT_WIDTH=500
+  DEFAULT_HALF_INIT_WIDTH=245
   saturation=100
-  init_width=500
+  init_width=$DEFAULT_INIT_WIDTH
   fuzz=2
   frame_interval=2
   last_delay=
@@ -308,6 +325,7 @@ function cli_gen() {
   blend_loop=0
   is_echo_convert=false
   output_gif=
+  is_half=false
   usage="Usage: $(basename "$0") [<option> [ ... ] ] <output_gif>
       -s,--saturation NUM     :
           set this smaller NUM if tumblr return \"Error uploading image\".
@@ -329,7 +347,10 @@ function cli_gen() {
       -b,--blend-loop NUM     :
           blending between the first frame and the last frame with NUM frame.
           default: $blend_loop
-      --echo-convert          : output 'convert' cmmands
+      --echo-convert          : just output 'convert' cmmands. does not execute.
+      --half                  :
+          generate a gif which be the half size and
+          the upper limit file size is 2MB.
       -h,--help
   "
   while [[ $# -gt 0 ]]; do
@@ -370,7 +391,13 @@ function cli_gen() {
               shift
               ;;
           --echo-convert)
-              is_echo_convert="true"
+              is_echo_convert=true
+              ;;
+          --half)
+              is_half=true
+              if [[ $init_width -eq $DEFAULT_INIT_WIDTH ]]
+              then init_width=$DEFAULT_HALF_INIT_WIDTH
+              fi
               ;;
           -h|--help) abort "$usage" ;;
           -*) abort "unknown option: $1" ;;
@@ -389,7 +416,7 @@ function cli_gen() {
   fi
   (
       for v in saturation init_width fuzz frame_interval last_delay delay_factor \
-          blend_loop is_echo_convert output_gif
+          blend_loop is_echo_convert is_half output_gif
       do eval echo "$v : \$$v"
       done
       echo -------------------
